#!/usr/bin/env node
// Idempotent patcher for the generated (gitignored) Capacitor ios/ project.
//
// Applies the native capabilities the WidgetKit widget + Siri intent need,
// without hand-editing Xcode files:
//
// 1. App Group entitlement (`com.apple.security.application-groups`) merged
//    into the host app entitlements AND a widget-extension entitlements file.
// 2. Widget target registration: committed Swift sources copied under
//    ios/App/BudgetLensWidget/ (with the App Group id stamped in) plus
//    marker-delimited, deterministically-generated project.pbxproj blocks
//    (file refs, build files, sources phase, appex target, build configs).
// 3. Info.plist keys: NSFaceIDUsageDescription ensured on the host app plist
//    (preserved when already set) and a generated widget extension plist.
//
// Idempotence: every edit is marker-guarded or content-compared, so re-running
// after `cap sync` is a byte-identical no-op. Verify without Xcode via
// `--dry-run` (prints per-file diffs, writes nothing) and `--check` (exit 1
// when drift is detected, for CI). Pure transforms are exported for unit
// tests; there are zero runtime dependencies (node: builtins only).
//
// Plain JavaScript on purpose (JSDoc types, no TS syntax): the file must run
// under any supported node AND import cleanly into vitest/rolldown.
//
// Deferred to the device-validation pass: `xcodebuild -list` / device build
// of the registered appex target, App Group container read/write on a real
// device, and the stock-Filesystem Documents staging -> group-container mover.

import { createHash } from "node:crypto"
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

export const DEFAULT_APP_GROUP = "group.com.cbangera2.budgetlens"
export const DEFAULT_APP_ID = "com.cbangera2.budgetlens"
export const WIDGET_TARGET_NAME = "BudgetLensWidget"
export const WIDGET_SOURCES = [
  "WidgetSnapshot.swift",
  "BudgetLensWidget.swift",
  "SpendingIntent.swift",
]
export const WIDGET_INFO_PLIST = "BudgetLensWidget-Info.plist"
export const WIDGET_ENTITLEMENTS = "BudgetLensWidget.entitlements"
export const APP_ENTITLEMENTS = "App.entitlements"
export const APP_GROUP_ENTITLEMENT_KEY = "com.apple.security.application-groups"
export const IOS_DEPLOYMENT_TARGET = "17.0"
export const APP_GROUP_TOKEN = "__APP_GROUP_ID__"
export const BLOCK_BEGIN =
  "BudgetLensWidget:begin - generated by scripts/ios-patcher.mjs; do not hand-edit"
export const BLOCK_END = "BudgetLensWidget:end"
export const TARGET_MARKER = "BudgetLensWidget:target"

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..")
const TEMPLATE_DIR = path.join(REPO_ROOT, "src", "features", "widget-bridge", "native")

/**
 * @typedef {object} PatcherOptions
 * @property {string} projectDir
 * @property {string} appGroup
 * @property {string} appId
 *
 * @typedef {object} FileChange
 * @property {string} path
 * @property {string | null} before
 * @property {string} after
 *
 * @typedef {object} TextEdit
 * @property {string} text
 * @property {boolean} changed
 *
 * @typedef {object} PbxprojEdit
 * @property {string} text
 * @property {boolean} changed
 * @property {string[]} notes
 *
 * @typedef {(relativePath: string) => string | null} ReadFile
 * @typedef {(name: string) => string} ReadTemplate
 *
 * @typedef {object} DiffLine
 * @property {" " | "-" | "+"} type
 * @property {string} text
 */

// ---------------------------------------------------------------------------
// Pure helpers (no fs): unit-tested via src/features/widget-bridge tests.
// ---------------------------------------------------------------------------

/**
 * Deterministic 24-hex Xcode-style id derived from a stable name.
 * @param {string} name
 * @returns {string}
 */
export function stableId(name) {
  return createHash("sha256").update(name, "utf8").digest("hex").slice(0, 24).toUpperCase()
}

/**
 * @param {string} value
 * @returns {string}
 */
export function escapeXml(value) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
}

/**
 * @param {string} value
 * @returns {string}
 */
function escapeRegExp(value) {
  return value.replaceAll(/[$()*+.?[\\\]^{|}]/g, "\\$&")
}

/**
 * Index of the `</dict>` closing the top-level `<dict>` of an XML plist.
 * @param {string} plistXml
 * @returns {number}
 */
export function topLevelDictCloseIndex(plistXml) {
  const plistOpen = plistXml.indexOf("<plist")
  if (plistOpen === -1) throw new Error("ios-patcher: not a plist document (missing <plist>).")
  const firstDict = plistXml.indexOf("<dict", plistOpen)
  if (firstDict === -1) throw new Error("ios-patcher: plist has no top-level <dict>.")
  const token = /<\/?dict(?=[\s>])/g
  token.lastIndex = firstDict
  let depth = 0
  let match = token.exec(plistXml)
  while (match) {
    depth += match[0].startsWith("</") ? -1 : 1
    if (depth === 0) return match.index
    match = token.exec(plistXml)
  }
  throw new Error("ios-patcher: unbalanced <dict> tags in plist.")
}

/**
 * Ensure a top-level `<key>` exists in an XML plist. Existing values are
 * preserved untouched; missing keys are inserted before the top-level close.
 * @param {string} plistXml
 * @param {string} key
 * @param {string} valueXml
 * @returns {TextEdit}
 */
export function ensureTopLevelDictKey(plistXml, key, valueXml) {
  if (plistXml.includes(`<key>${key}</key>`)) return { text: plistXml, changed: false }
  const close = topLevelDictCloseIndex(plistXml)
  const indentMatch = /\n([ \t]*)$/.exec(plistXml.slice(0, close))
  const indent = indentMatch && indentMatch[1] !== undefined ? indentMatch[1] : "\t"
  const entry = `\n${indent}<key>${key}</key>\n${indent}${valueXml}`
  return { text: `${plistXml.slice(0, close)}${entry}\n${plistXml.slice(close)}`, changed: true }
}

/**
 * @param {string} groupId
 * @returns {string}
 */
function freshEntitlements(groupId) {
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`,
    `<plist version="1.0">`,
    `<dict>`,
    `\t<key>${APP_GROUP_ENTITLEMENT_KEY}</key>`,
    `\t<array><string>${escapeXml(groupId)}</string></array>`,
    `</dict>`,
    `</plist>`,
    ``,
  ].join("\n")
}

/**
 * Ensure the App Group entitlement array contains `groupId`. Creates a fresh
 * entitlements document when none exists; preserves all unrelated keys.
 * @param {string | null} existingXml
 * @param {string} groupId
 * @returns {TextEdit}
 */
export function ensureAppGroupEntitlements(existingXml, groupId) {
  if (existingXml === null) return { text: freshEntitlements(groupId), changed: true }
  if (!existingXml.trimStart().startsWith("<?xml")) {
    throw new Error("ios-patcher: entitlements file is not an XML plist; refusing to edit.")
  }
  const keyTag = `<key>${APP_GROUP_ENTITLEMENT_KEY}</key>`
  if (!existingXml.includes(keyTag)) {
    return ensureTopLevelDictKey(
      existingXml,
      APP_GROUP_ENTITLEMENT_KEY,
      `<array><string>${escapeXml(groupId)}</string></array>`,
    )
  }
  const afterKey = existingXml.indexOf(keyTag) + keyTag.length
  const arrayOpen = existingXml.indexOf("<array", afterKey)
  const headTag = /^\s*<([A-Za-z]+)[\s>]/.exec(existingXml.slice(afterKey))
  if (arrayOpen === -1 || !headTag || headTag[1] !== "array") {
    throw new Error(
      `ios-patcher: ${APP_GROUP_ENTITLEMENT_KEY} exists but is not an <array>; fix it by hand.`,
    )
  }
  const arrayClose = existingXml.indexOf("</array>", arrayOpen)
  if (arrayClose === -1) throw new Error("ios-patcher: unbalanced <array> in entitlements.")
  const inner = existingXml.slice(arrayOpen, arrayClose)
  const needle = new RegExp(`<string>\\s*${escapeRegExp(groupId)}\\s*</string>`)
  if (needle.test(inner)) return { text: existingXml, changed: false }
  return {
    text: `${existingXml.slice(0, arrayClose)}<string>${escapeXml(groupId)}</string>${existingXml.slice(arrayClose)}`,
    changed: true,
  }
}

/**
 * Generated widget-extension Info.plist (WidgetKit NSExtension).
 * @returns {string}
 */
export function buildWidgetExtensionPlist() {
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">`,
    `<plist version="1.0">`,
    `<dict>`,
    `\t<key>CFBundleDisplayName</key>`,
    `\t<string>BudgetLens</string>`,
    `\t<key>CFBundleShortVersionString</key>`,
    `\t<string>1.0</string>`,
    `\t<key>CFBundleVersion</key>`,
    `\t<string>1</string>`,
    `\t<key>NSExtension</key>`,
    `\t<dict>`,
    `\t\t<key>NSExtensionPointIdentifier</key>`,
    `\t\t<string>com.apple.widgetkit-extension</string>`,
    `\t</dict>`,
    `</dict>`,
    `</plist>`,
    ``,
  ].join("\n")
}

/**
 * @param {string} section
 * @param {string} inner
 * @returns {string}
 */
function markedBlock(section, inner) {
  return `/* ${BLOCK_BEGIN} [${section}] */\n${inner}\n/* ${BLOCK_END} [${section}] */`
}

/**
 * Replace an existing marked block or insert it before the section end.
 * @param {string} text
 * @param {string} section
 * @param {string} inner
 * @returns {TextEdit}
 */
export function upsertMarkedBlock(text, section, inner) {
  const begin = `/* ${BLOCK_BEGIN} [${section}] */`
  const end = `/* ${BLOCK_END} [${section}] */`
  const pattern = new RegExp(`${escapeRegExp(begin)}[\\s\\S]*?${escapeRegExp(end)}`)
  const block = markedBlock(section, inner)
  if (pattern.test(text)) {
    const next = text.replace(pattern, () => block)
    return { text: next, changed: next !== text }
  }
  const anchor = `/* End ${section} section */`
  if (!text.includes(anchor)) {
    throw new Error(
      `ios-patcher: project.pbxproj is missing "${anchor}"; regenerate ios/ via "cap add ios".`,
    )
  }
  return { text: text.replace(anchor, () => `${block}\n${anchor}`), changed: true }
}

/**
 * @returns {{ files: Record<string, string>, builds: Record<string, string>, product: string, entitlements: string, infoPlist: string, sourcesPhase: string, target: string, configList: string, configDebug: string, configRelease: string }}
 */
function widgetIds() {
  const id = (kind, name) => stableId(`BudgetLensWidget:${kind}:${name}`)
  const files = Object.fromEntries(WIDGET_SOURCES.map((name) => [name, id("file", name)]))
  const builds = Object.fromEntries(WIDGET_SOURCES.map((name) => [name, id("build", name)]))
  return {
    files,
    builds,
    product: id("product", "appex"),
    entitlements: id("file", "entitlements"),
    infoPlist: id("file", "info-plist"),
    sourcesPhase: id("phase", "sources"),
    target: id("target", "widget"),
    configList: id("config", "list"),
    configDebug: id("config", "debug"),
    configRelease: id("config", "release"),
  }
}

/**
 * Apply the widget target registration to project.pbxproj text. All inserted
 * ids are deterministic (see {@link stableId}), so re-running is stable.
 * @param {string} text
 * @param {{ appId: string }} context
 * @returns {PbxprojEdit}
 */
export function applyPbxprojEdits(text, context) {
  const notes = []
  let changed = false
  let next = text
  const ids = widgetIds()
  const t = (value) => `\t\t${value}`

  const track = (section, inner) => {
    const result = upsertMarkedBlock(next, section, inner)
    next = result.text
    if (result.changed) {
      changed = true
      notes.push(section)
    }
  }

  track(
    "PBXFileReference",
    [
      ...WIDGET_SOURCES.map((name) =>
        t(
          `${ids.files[name]} /* ${name} */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = ${name}; sourceTree = "<group>"; };`,
        ),
      ),
      t(
        `${ids.infoPlist} /* ${WIDGET_INFO_PLIST} */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = ${WIDGET_INFO_PLIST}; sourceTree = "<group>"; };`,
      ),
      t(
        `${ids.entitlements} /* ${WIDGET_ENTITLEMENTS} */ = {isa = PBXFileReference; lastKnownFileType = text.plist.entitlements; path = ${WIDGET_ENTITLEMENTS}; sourceTree = "<group>"; };`,
      ),
      t(
        `${ids.product} /* ${WIDGET_TARGET_NAME}.appex */ = {isa = PBXFileReference; explicitFileType = "wrapper.app-extension"; includeInIndex = 0; path = ${WIDGET_TARGET_NAME}.appex; sourceTree = BUILT_PRODUCTS_DIR; };`,
      ),
    ].join("\n"),
  )

  track(
    "PBXBuildFile",
    WIDGET_SOURCES.map((name) =>
      t(
        `${ids.builds[name]} /* ${name} in Sources */ = {isa = PBXBuildFile; fileRef = ${ids.files[name]} /* ${name} */; };`,
      ),
    ).join("\n"),
  )

  track(
    "PBXSourcesBuildPhase",
    [
      t(`${ids.sourcesPhase} /* Sources */ = {`),
      t(`\tisa = PBXSourcesBuildPhase;`),
      t(`\tbuildActionMask = 2147483647;`),
      t(`\tfiles = (`),
      ...WIDGET_SOURCES.map((name) => t(`\t\t${ids.builds[name]} /* ${name} in Sources */,`)),
      t(`\t);`),
      t(`\trunOnlyForDeploymentPostprocessing = 0;`),
      t(`};`),
    ].join("\n"),
  )

  track(
    "PBXNativeTarget",
    [
      t(`${ids.target} /* ${WIDGET_TARGET_NAME} */ = {`),
      t(`\tisa = PBXNativeTarget;`),
      t(
        `\tbuildConfigurationList = ${ids.configList} /* Build configuration list for PBXNativeTarget "${WIDGET_TARGET_NAME}" */;`,
      ),
      t(`\tbuildPhases = (`),
      t(`\t\t${ids.sourcesPhase} /* Sources */,`),
      t(`\t);`),
      t(`\tbuildRules = (`),
      t(`\t);`),
      t(`\tdependencies = (`),
      t(`\t);`),
      t(`\tname = ${WIDGET_TARGET_NAME};`),
      t(`\tproductName = ${WIDGET_TARGET_NAME};`),
      t(`\tproductReference = ${ids.product} /* ${WIDGET_TARGET_NAME}.appex */;`),
      t(`\tproductType = "com.apple.product-type.app-extension";`),
      t(`};`),
    ].join("\n"),
  )

  const buildSettings = (name) => {
    const lines = [
      t(`\t\t\t\tAPPLICATION_EXTENSION_API_ONLY = YES;`),
      t(`\t\t\t\tCODE_SIGN_ENTITLEMENTS = "${WIDGET_TARGET_NAME}/${WIDGET_ENTITLEMENTS}";`),
      t(`\t\t\t\tCODE_SIGN_STYLE = Automatic;`),
      t(`\t\t\t\tCURRENT_PROJECT_VERSION = 1;`),
      t(`\t\t\t\tINFOPLIST_FILE = "${WIDGET_TARGET_NAME}/${WIDGET_INFO_PLIST}";`),
      t(`\t\t\t\tIPHONEOS_DEPLOYMENT_TARGET = ${IOS_DEPLOYMENT_TARGET};`),
      t(`\t\t\t\tMARKETING_VERSION = 1.0;`),
      t(`\t\t\t\tPRODUCT_BUNDLE_IDENTIFIER = "${context.appId}.widget";`),
      t(`\t\t\t\tPRODUCT_NAME = "$(TARGET_NAME)";`),
      t(`\t\t\t\tSKIP_INSTALL = YES;`),
      t(`\t\t\t\tSWIFT_VERSION = 5.9;`),
    ]
    if (name === "Debug") lines.push(t(`\t\t\t\tSWIFT_OPTIMIZATION_LEVEL = "-Onone";`))
    return lines.join("\n")
  }

  const configEntry = (id, name) =>
    [
      t(`${id} /* ${name} */ = {`),
      t(`\tisa = XCBuildConfiguration;`),
      t(`\tbuildSettings = {`),
      buildSettings(name),
      t(`\t};`),
      t(`\tname = ${name};`),
      t(`};`),
    ].join("\n")

  track(
    "XCBuildConfiguration",
    `${configEntry(ids.configDebug, "Debug")}\n${configEntry(ids.configRelease, "Release")}`,
  )

  track(
    "XCConfigurationList",
    [
      t(
        `${ids.configList} /* Build configuration list for PBXNativeTarget "${WIDGET_TARGET_NAME}" */ = {`,
      ),
      t(`\tisa = XCConfigurationList;`),
      t(`\tbuildConfigurations = (`),
      t(`\t\t${ids.configDebug} /* Debug */,`),
      t(`\t\t${ids.configRelease} /* Release */,`),
      t(`\t);`),
      t(`\tdefaultConfigurationIsVisible = 0;`),
      t(`\tdefaultConfigurationName = Release;`),
      t(`};`),
    ].join("\n"),
  )

  if (!next.includes(TARGET_MARKER)) {
    const pattern = /(targets = \(\n[\s\S]*?)(\n[ \t]*\);)/
    if (!pattern.test(next)) {
      throw new Error('ios-patcher: project.pbxproj has no "targets = (...)" array to extend.')
    }
    const line = `\n\t\t\t\t${ids.target} /* ${WIDGET_TARGET_NAME} */, // ${TARGET_MARKER}`
    next = next.replace(pattern, (_match, head, tail) => `${head}${line}${tail}`)
    changed = true
    notes.push("PBXProject-targets")
  }

  return { text: next, changed, notes }
}

/**
 * Minimal line diff for --dry-run output.
 * @param {string} before
 * @param {string} after
 * @returns {DiffLine[]}
 */
export function diffLines(before, after) {
  const a = before.split("\n")
  const b = after.split("\n")
  const rows = Array.from({ length: a.length + 1 }, () => new Array(b.length + 1).fill(0))
  for (let i = a.length - 1; i >= 0; i -= 1) {
    for (let j = b.length - 1; j >= 0; j -= 1) {
      const same = a[i] === b[j] ? 1 : 0
      const diag =
        rows[i + 1] !== undefined && rows[i + 1][j + 1] !== undefined ? rows[i + 1][j + 1] : 0
      const down = rows[i + 1] !== undefined && rows[i + 1][j] !== undefined ? rows[i + 1][j] : 0
      const right = rows[i] !== undefined && rows[i][j + 1] !== undefined ? rows[i][j + 1] : 0
      rows[i][j] = same === 1 ? diag + 1 : Math.max(down, right)
    }
  }
  const get = (i, j) => (rows[i] !== undefined && rows[i][j] !== undefined ? rows[i][j] : 0)
  /** @type {DiffLine[]} */
  const out = []
  let i = 0
  let j = 0
  while (i < a.length && j < b.length) {
    if (a[i] === b[j]) {
      out.push({ type: " ", text: a[i] === undefined ? "" : a[i] })
      i += 1
      j += 1
    } else if (get(i + 1, j) >= get(i, j + 1)) {
      out.push({ type: "-", text: a[i] === undefined ? "" : a[i] })
      i += 1
    } else {
      out.push({ type: "+", text: b[j] === undefined ? "" : b[j] })
      j += 1
    }
  }
  while (i < a.length) {
    out.push({ type: "-", text: a[i] === undefined ? "" : a[i] })
    i += 1
  }
  while (j < b.length) {
    out.push({ type: "+", text: b[j] === undefined ? "" : b[j] })
    j += 1
  }
  return out
}

// ---------------------------------------------------------------------------
// Filesystem plan + CLI (thin wrapper over the pure transforms above).
// ---------------------------------------------------------------------------

/**
 * Compute every file write the patcher wants; performs no IO itself.
 * @param {ReadFile} readFile
 * @param {ReadTemplate} readTemplate
 * @param {PatcherOptions} options
 * @returns {FileChange[]}
 */
export function planProjectEdits(readFile, readTemplate, options) {
  /** @type {FileChange[]} */
  const changes = []
  const consider = (relativePath, before, after) => {
    if (before !== after) changes.push({ path: relativePath, before, after })
  }

  const entitlementsPath = path.join("App", APP_ENTITLEMENTS)
  const entitlementsBefore = readFile(entitlementsPath)
  consider(
    entitlementsPath,
    entitlementsBefore,
    ensureAppGroupEntitlements(entitlementsBefore, options.appGroup).text,
  )

  const infoPlistPath = path.join("App", "Info.plist")
  const infoBefore = readFile(infoPlistPath)
  if (infoBefore === null) {
    throw new Error(`ios-patcher: missing ${infoPlistPath}; regenerate ios/ via "cap add ios".`)
  }
  consider(
    infoPlistPath,
    infoBefore,
    ensureTopLevelDictKey(
      infoBefore,
      "NSFaceIDUsageDescription",
      "<string>Unlock BudgetLens with Face ID or your device passcode.</string>",
    ).text,
  )

  for (const name of WIDGET_SOURCES) {
    const template = readTemplate(name)
    if (!template.includes(APP_GROUP_TOKEN)) {
      throw new Error(`ios-patcher: template ${name} is missing the ${APP_GROUP_TOKEN} token.`)
    }
    const targetPath = path.join("App", WIDGET_TARGET_NAME, name)
    consider(
      targetPath,
      readFile(targetPath),
      template.replaceAll(APP_GROUP_TOKEN, options.appGroup),
    )
  }

  const widgetPlistPath = path.join("App", WIDGET_TARGET_NAME, WIDGET_INFO_PLIST)
  consider(widgetPlistPath, readFile(widgetPlistPath), buildWidgetExtensionPlist())

  const widgetEntitlementsPath = path.join("App", WIDGET_TARGET_NAME, WIDGET_ENTITLEMENTS)
  const widgetEntitlementsBefore = readFile(widgetEntitlementsPath)
  consider(
    widgetEntitlementsPath,
    widgetEntitlementsBefore,
    ensureAppGroupEntitlements(widgetEntitlementsBefore, options.appGroup).text,
  )

  const pbxprojPath = path.join("App.xcodeproj", "project.pbxproj")
  const pbxprojBefore = readFile(pbxprojPath)
  if (pbxprojBefore === null) {
    throw new Error(`ios-patcher: missing ${pbxprojPath}; regenerate ios/ via "cap add ios".`)
  }
  consider(
    pbxprojPath,
    pbxprojBefore,
    applyPbxprojEdits(pbxprojBefore, { appId: options.appId }).text,
  )

  return changes
}

/**
 * @param {string} capacitorConfigPath
 * @returns {string}
 */
function readAppId(capacitorConfigPath) {
  try {
    const text = readFileSync(capacitorConfigPath, "utf8")
    const match = /appId:\s*"([^"]+)"/.exec(text)
    if (match && match[1]) return match[1]
  } catch {
    // Fall through to the default below.
  }
  return DEFAULT_APP_ID
}

/**
 * @param {string[]} argv
 */
function parseArgs(argv) {
  let projectDir = path.join(REPO_ROOT, "ios")
  let appGroup = DEFAULT_APP_GROUP
  let appId = null
  let dryRun = false
  let check = false
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]
    if (arg === "--project") {
      const value = argv[i + 1]
      if (!value) throw new Error("ios-patcher: --project needs a directory value.")
      projectDir = path.resolve(value)
      i += 1
    } else if (arg === "--app-group") {
      const value = argv[i + 1]
      if (!value) throw new Error("ios-patcher: --app-group needs a group id value.")
      appGroup = value
      i += 1
    } else if (arg === "--app-id") {
      const value = argv[i + 1]
      if (!value) throw new Error("ios-patcher: --app-id needs a bundle id value.")
      appId = value
      i += 1
    } else if (arg === "--dry-run") {
      dryRun = true
    } else if (arg === "--check") {
      check = true
    } else if (arg === "--help" || arg === "-h") {
      printHelp()
      process.exit(0)
    } else {
      throw new Error(`ios-patcher: unknown argument "${arg}". See --help.`)
    }
  }
  return { projectDir, appGroup, appId, dryRun, check }
}

function printHelp() {
  // oxlint-disable-next-line no-console -- CLI help output.
  console.log(
    [
      "Usage: node scripts/ios-patcher.mjs [options]",
      "",
      "Applies BudgetLens widget capabilities to the generated ios/ project.",
      "",
      "Options:",
      "  --project <dir>    ios project root (default: <repo>/ios)",
      "  --app-group <id>   App Group id (default: group.com.cbangera2.budgetlens)",
      "  --app-id <id>      host app bundle id (default: read from capacitor.config.ts)",
      "  --dry-run          print per-file diffs, write nothing",
      "  --check            exit 1 when any file would change (CI drift gate)",
      "  --help             this text",
    ].join("\n"),
  )
}

/**
 * @param {FileChange} change
 */
function printDiff(change) {
  const before = change.before === null || change.before === undefined ? "" : change.before
  const hunks = diffLines(before, change.after).filter((line) => line.type !== " ")
  // oxlint-disable-next-line no-console -- CLI diff output.
  console.log(`--- ${change.path} (${change.before === null ? "new" : "modified"})`)
  const shown = hunks.slice(0, 120)
  for (const line of shown) {
    // oxlint-disable-next-line no-console -- CLI diff output.
    console.log(`${line.type} ${line.text}`)
  }
  if (hunks.length > shown.length) {
    // oxlint-disable-next-line no-console -- CLI diff output.
    console.log(`... (${hunks.length - shown.length} more changed lines)`)
  }
}

/**
 * @param {string[]} argv
 */
function main(argv) {
  let parsed
  try {
    parsed = parseArgs(argv)
  } catch (error) {
    // oxlint-disable-next-line no-console -- CLI error output.
    console.error(error instanceof Error ? error.message : String(error))
    process.exitCode = 1
    return
  }
  if (!existsSync(parsed.projectDir)) {
    // oxlint-disable-next-line no-console -- CLI error output.
    console.error(
      `ios-patcher: project not found at ${parsed.projectDir}; run "pnpm prebuild:ios" (cap add ios) first.`,
    )
    process.exitCode = 1
    return
  }
  const appId =
    parsed.appId === null ? readAppId(path.join(REPO_ROOT, "capacitor.config.ts")) : parsed.appId
  /** @type {ReadFile} */
  const readFile = (relativePath) => {
    const absolute = path.join(parsed.projectDir, relativePath)
    return existsSync(absolute) ? readFileSync(absolute, "utf8") : null
  }
  /** @type {ReadTemplate} */
  const readTemplate = (name) => readFileSync(path.join(TEMPLATE_DIR, name), "utf8")
  /** @type {FileChange[]} */
  let changes
  try {
    changes = planProjectEdits(readFile, readTemplate, {
      projectDir: parsed.projectDir,
      appGroup: parsed.appGroup,
      appId,
    })
  } catch (error) {
    // oxlint-disable-next-line no-console -- CLI error output.
    console.error(error instanceof Error ? error.message : String(error))
    process.exitCode = 1
    return
  }
  if (parsed.check) {
    if (changes.length > 0) {
      // oxlint-disable-next-line no-console -- CLI drift output.
      console.log(
        `ios-patcher: drift detected in ${changes.length} file(s): ${changes.map((change) => change.path).join(", ")}`,
      )
      process.exitCode = 1
    } else {
      // oxlint-disable-next-line no-console -- CLI status output.
      console.log("ios-patcher: project is clean, no changes needed.")
    }
    return
  }
  if (parsed.dryRun) {
    if (changes.length === 0) {
      // oxlint-disable-next-line no-console -- CLI status output.
      console.log("ios-patcher: project is clean, no changes needed.")
    }
    for (const change of changes) printDiff(change)
    // oxlint-disable-next-line no-console -- CLI status output.
    console.log(`ios-patcher: ${changes.length} file(s) would change (dry run, nothing written).`)
    return
  }
  for (const change of changes) {
    const absolute = path.join(parsed.projectDir, change.path)
    mkdirSync(path.dirname(absolute), { recursive: true })
    writeFileSync(absolute, change.after, "utf8")
    // oxlint-disable-next-line no-console -- CLI status output.
    console.log(`ios-patcher: ${change.before === null ? "created" : "updated"} ${change.path}`)
  }
  // oxlint-disable-next-line no-console -- CLI status output.
  console.log(`ios-patcher: done, ${changes.length} file(s) changed.`)
}

const invokedAsScript =
  process.argv[1] != null && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])

if (invokedAsScript) {
  main(process.argv.slice(2))
}
